export const products = [
	{
		id: "1",
		name: "Tech Blog",
		type: "website",
		price: 5000,
		description: "Established tech blog with 10k monthly visitors",
		images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
		age: 24,
		monetization: "AdSense",
		earningsPerMonth: 500,
		seller: {
			name: "John Doe",
			rating: 4.8,
			totalSales: 15,
			memberSince: "2020-01-01",
		},
	},
	{
		id: "2",
		name: "Gadget Reviews",
		type: "youtube",
		price: 7500,
		description: "YouTube channel with 50k subscribers",
		images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
		age: 36,
		monetization: "AdSense, Sponsorships",
		earningsPerMonth: 1200,
		seller: {
			name: "John Doe",
			rating: 4.8,
			totalSales: 15,
			memberSince: "2020-01-01",
		},
	},
	{
		id: "3",
		name: "Travel Photography",
		type: "instagram",
		price: 3000,
		description: "Instagram account with 25k followers",
		images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
		age: 18,
		monetization: "Sponsored Posts",
		earningsPerMonth: 800,
		seller: {
			name: "John Doe",
			rating: 4.8,
			totalSales: 15,
			memberSince: "2020-01-01",
		},
	},
	{
		id: "4",
		name: "Fitness Community",
		type: "facebook",
		price: 4000,
		description: "Facebook page with 30k likes",
		images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
		age: 30,
		monetization: "Affiliate Marketing",
		earningsPerMonth: 600,
		seller: {
			name: "John Doe",
			rating: 4.8,
			totalSales: 15,
			memberSince: "2020-01-01",
		},
	},
	{
		id: "5",
		name: "E-commerce Store",
		type: "website",
		price: 10000,
		description: "Shopify store with $5k monthly revenue",
		images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
		age: 12,
		monetization: "Product Sales",
		earningsPerMonth: 2000,
		seller: {
			name: "John Doe",
			rating: 4.8,
			totalSales: 15,
			memberSince: "2020-01-01",
		},
	},
	{
		id: "6",
		name: "Cooking Tutorials",
		type: "youtube",
		price: 6000,
		description: "Cooking channel with 40k subscribers",
		images: ["/placeholder.jpg", "/placeholder.jpg", "/placeholder.jpg"],
		age: 48,
		monetization: "AdSense, Merchandise",
		earningsPerMonth: 1500,
		seller: {
			name: "John Doe",
			rating: 4.8,
			totalSales: 15,
			memberSince: "2020-01-01",
		},
	},
];
